[package]
name = "b3"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"
authors = ["Andrej KolÄin <self@kaathewise.net>"]

[dependencies]
base = { path ="../base" }
glam = "0.29.2"
nalgebra = { workspace = true, features = ["convert-glam029"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "likelihood"
harness = false
