[package]
name = "b3"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"
authors = ["Andrej KolÄin <self@kaathewise.net>"]

[dependencies]
base = { path ="../base" }

nalgebra = { workspace = true }
rand_xoshiro = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
wide = { workspace = true }

[dev-dependencies]
criterion = { workspace = true, features = ["html_reports"] }

[[bench]]
name = "likelihood"
harness = false
