[package]
name = "b3"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"
authors = ["Andrej KolÄin <self@kaathewise.net>"]

[dependencies]
base = { path ="../base" }
nalgebra = { workspace = true }
wide = "0.7.28"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "likelihood"
harness = false
